### ISSUE TITLE
Songs listed as "unseen lyrics" have lyrics from real life songs

### ISSUE THREAD

**Issue by fisadev** [openai/jukebox#10]
Many songs listed in the "unseen lyrics" collection have almost exact copies of the lyrics from real life songs.

Some examples:

![image](https://user-images.githubusercontent.com/251215/80748609-90dc4300-8afb-11ea-8ad4-cb4dbf581981.png)

That's most of Family Table, by Zac Brown Band.

![image](https://user-images.githubusercontent.com/251215/80748686-b36e5c00-8afb-11ea-9d5c-87e95e71a729.png)

Same again.

![image](https://user-images.githubusercontent.com/251215/80748765-d436b180-8afb-11ea-9735-64044952e379.png)

That's from Spaceman, by 4 Non Blondes.

And so on.

So there are some serious overfitting issues in the lyrics generation, and they weren't noticed.

**Comment by prafullasd** [comment]
Unseen lyrics meant lyrics not seen by model during training, so these lyrics were chosen from songs not in training set, plus lyrics generated from language models.

**Comment by prafullasd** [comment]
Note Jukebox doesnt generate the lyrics text itself, it conditions on the text we provide it to generate the music + singing.

**Comment by fisadev** [comment]
ooh! ok, that makes more sense. It wasn't that clear in the website, though. Sorry for the confusion :)
