### ISSUE TITLE
Loading from checkpoint: name 'zs' is not defined

### ISSUE THREAD

**Issue by eryksalvaggio** [openai/jukebox#105]
Running on CoLab, at the spot where it asks me to load the zs-top-level-final.t file. I have one from a session that crashed. I reload the runtime and run the top cells again, upload the zs-top-level-final.t file to the folder, then skip to "Upsample Co-Composition to Higher Audio Quality." 

When I load it (using the full path of the file) in the cell, I get the error that "name 'zs' is not defined." It appears to me that I am defining it as the directory path. I don't see anywhere else to initialize that variable. Is this a bug, or am I missing something?  Thanks. 

![zs](https://user-images.githubusercontent.com/24421883/83958302-6aa48280-a8b3-11ea-8d3b-68b8f62c61bf.JPG)

**Comment by anlexmatos** [comment]
Where it says
`if False:`
You need to change it to:
`If True:`

It's set to false by default with the intention that it's unnecessary to reload zs if you aren't restarting from a previous session.

**Comment by eryksalvaggio** [comment]
Thank you. That worked, though I also had to go back and set the 5b or 1b model in the "Co-Composing" section, in case anyone else has this issue. I had skipped it as I'd assumed the "co-composing" pieces wouldn't be useful to upscaling. Thanks!

**Comment by upinthewoodsdownonmymind** [comment]
Im having this same error on the normal mode when upsampling, can someone help?
