### ISSUE TITLE
Lyrics Conditioning

### ISSUE THREAD

**Issue by loretoparisi** [openai/jukebox#11]
Is the lyrics Conditioning only at training time or is it possible to seed the model with own lyrics in the same way as is possible with _wav_ input here

python jukebox/sample.py --model=5b_lyrics --name=sample_5b_prompted --levels=3 --mode=primed --audio_file=path/to/recording.wav,awesome-mix.wav,fav-song.wav,etc.wav --prompt_length_in_seconds=12 --sample_length_in_seconds=20 --total_sample_length_in_seconds=180 --sr=44100 --n_samples=6 --hop_fraction=0.5,0.5,0.125

**Comment by prafullasd** [comment]
Yes you definately can pass you own lyrics, artist and genre! Just edit the values passed in sample.py in metas!

**Comment by prafullasd** [comment]
We'll try to add a command line script to pass these args to make this easier

**Comment by loretoparisi** [comment]
Amazing thank you waiting for the docs then. Will try sample.py in the meanwhile!

**Comment by loretoparisi** [comment]
@prafullasd Thank you I managed to condition the model through the  new Colab. We have noticed that  there are some “unpredictable” tokens or better not understandable words in the singing voice generation. Could this be due to the training vocabulary used for the GPT-2 model, that may have a unseen tokens in our input?

**Comment by heewooj** [comment]
[This line](https://github.com/openai/jukebox/blob/master/jukebox/data/text_processor.py#L22) removes OOV characters. It's possible that two words are joined together resulting in a word the model has not seen before. You can normalize the lyrics yourself or try sampling more.

**Comment by loretoparisi** [comment]
@heewooj thank you, closing then.

**Comment by cozec** [comment]
> @prafullasd Thank you I managed to condition the model through the new Colab. We have noticed that there are some “unpredictable” tokens or better not understandable words in the singing voice generation. Could this be due to the training vocabulary used for the GPT-2 model, that may have a unseen tokens in our input?

You mind sharing how you do it, by condition on lyric?
