### ISSUE TITLE
403 error when downloading 1b model

### ISSUE THREAD

**Issue by mvassilevsky** [openai/jukebox#111]
I'm on Windows, so I'm downloading the model files manually as shown [here](https://github.com/openai/jukebox/issues/92#issuecomment-634128316). I can download most of them without problems, whether with wget or directly from my browser, but `https://storage.googleapis.com/jukebox-assets/models/1b/prior_level_2.pth.tar` gets a 403 Forbidden response with wget and
```
<Error>
  <Code>AccessDenied</Code>
  <Message>Access denied.</Message>
  <Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details>
</Error>
```
if I try to access it directly with my browser.

**Comment by boussaffawalid** [comment]
Having the exact same issue, is there any update?

**Comment by datalee** [comment]
me too

**Comment by jongwook** [comment]
There was a typo in the comment linked above. Please use `1b_lyrics` instead of `1b`.
