### ISSUE TITLE
Assertion Error during upsampling

### ISSUE THREAD

**Issue by eryksalvaggio** [openai/jukebox#112]
Trying to upsample a zs-top-level-final.t that hadn't completed from a previous session. Running in Colab P100 GPU. Loaded all cells no problem, but then the final step won't start, giving me: 

AssertionError: Expected shape (3,**), got shape torch.Size([4, 9])

Image for reference. 
![assertionerror](https://user-images.githubusercontent.com/24421883/84386334-7d60e380-ac34-11ea-9376-ed5f2d25ec11.JPG)

Haven't encountered this before.

**Comment by anlexmatos** [comment]
I've experienced something like this when the values set in previous cells don't match their value from the previous session. 

In the cells above, make sure that the values assigned to `hps.n_samples`, `chunk_size`, `max_batch_size`, `lower_batch_size`, and `lower_level_chunk_size` are all set the same as they were when your zs-top-level-final.t was originally created.

**Comment by eryksalvaggio** [comment]
Thanks @anlexmatos. You're right, in between the failed save and the re-attempt, I had changed the max_batch_size to create fewer samples and save memory. Good catch.
