### ISSUE TITLE
Inconsistent artist info between V2 and V3.

### ISSUE THREAD

**Issue by ApexJohn** [openai/jukebox#122]
So over the course of using this I've noticed that there's some artists missing in V2, and V3 of the ID lists. For example R.E.M., Dave Matthews Band, Rage Against the Machine and Radiohead are present in the V2 dataset, but not in V3. The same goes for V3 artists in V2, while there's many more examples of that one artist I noticed is Negativland, which when trying to use it as an input it throws an error saying the artist isn't in V2. 

Questions:
If I use artists in V2 but not V3, is that artists data actually being used? Or is it defaulting to "unknown" since the artist isn't in V3.
Are artists from V3 accessible in the dataset if V2 is modified? Or is it not possible to access training data done for those.

**Comment by anlexmatos** [comment]
The v2 labels represent the data on which the 5b models were trained, while the v3 labels represent the data on which 1b_lyrics was trained.

You should direct your usage accordingly: only use artist and genre labels from v2 if you are sampling from 5b, and only use those from v3 if you are sampling from 1b.

**Comment by moonsh** [comment]
@anlexmatos  Just curious. Is that possible to change the genre at the last stage sampling? so I could get a different type of music with the same input?
