### ISSUE TITLE
Can you provide a TPU version of jukebox so that I can accelerate the computation?

### ISSUE THREAD

**Issue by shyamalschandra** [openai/jukebox#13]
Can you provide a TPU version of jukebox so that I can accelerate the computation?

I would highly recommend providing a Colab Notebook for executing the scripts for jukebox with CPU, GPU, and TPU.

**Comment by prafullasd** [comment]
We don't plan on adding support for new hardware. 
The community is welcome to try to do so! :)

**Comment by shyamalschandra** [comment]
@prafullasd , could you at least provide a local version for a non-CUDA GPU or traditional CPU?
