### ISSUE TITLE
Error at processing level 0 music.

### ISSUE THREAD

**Issue by RenatoFome** [openai/jukebox#138]
I am getting a error at the last code; this is showing to me:
"---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-08acfa06397a> in <module>()
----> 1 zs = upsample(zs, labels, sampling_kwargs, [*samplers, top_prior], hps)

NameError: name 'upsample' is not defined"
I don't know about a little of code, so can anyone tell me what i can do to  correct this?

edit: Now getting another error:
"---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-20-8b3a8268585a> in <module>()
----> 1 zs = upsample(zs, labels, sampling_kwargs, [*upsamplers, top_prior], hps)

NameError: name 'zs' is not defined"

**Comment by denishot** [comment]
xineohpoel
