### ISSUE TITLE
How can I generate music without lyrics?

### ISSUE THREAD

**Issue by Apokar** [openai/jukebox#148]
How can I generate music without lyrics?
I tried use 5b model and set lyrics="",artist="" 
But I still got some words in the music I generated

Thx for any help !

**Comment by DigestContent0** [comment]
I recommend using a Spleeter (download needed) or Vocalremover.org (uses Spleeter automatically) to remove uneeded vocals.

**Comment by Apokar** [comment]
@DigestContent0  It's a good way to solve the problem. Thx
