### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by lntrinsix** [openai/jukebox#149]
Trying to get Jukebox working on Windows 10. I have an NVIDIA 2080 graphics card.
My code: https://pastebin.com/zdLtFvEs
Output:
C:\Users\Intrinsix\jukebox>python Intrinsix.py
C:\Users\Intrinsix\jukebox\jukebox\utils\gcs_utils.py:41: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  outputs = [output for output in outputs if output is not '']
Using cuda True

C:\Users\Intrinsix\jukebox>python Intrinsix.py
Using cuda True
Downloading from gce
Traceback (most recent call last):
  File "Intrinsix.py", line 32, in <module>
    vqvae = make_vqvae(setup_hparams(vqvae, dict(sample_length = 1048576)), device)
  File "C:\Users\Intrinsix\jukebox\jukebox\make_models.py", line 95, in make_vqvae
    restore_model(hps, vqvae, hps.restore_vqvae)
  File "C:\Users\Intrinsix\jukebox\jukebox\make_models.py", line 55, in restore_model
    checkpoint = load_checkpoint(checkpoint_path)
  File "C:\Users\Intrinsix\jukebox\jukebox\make_models.py", line 34, in load_checkpoint
    download(gs_path, local_path)
  File "C:\Users\Intrinsix\jukebox\jukebox\utils\gcs_utils.py", line 36, in download
    subprocess.call(args)
  File "C:\Users\Intrinsix\miniconda3\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Intrinsix\miniconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Intrinsix\miniconda3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by Boii1** [comment]
Same error.

**Comment by jongwook** [comment]
The current codebase Jukebox does not support Windows out-of-the-box, but it seems possible with a few modifications. Check out [a windows port](https://github.com/peterlazzarino/jukebox-windows) or try [CUDA on WSL](https://docs.nvidia.com/cuda/wsl-user-guide/index.html).

**Comment by cicinwad** [comment]
> Trying to get Jukebox working on Windows 10. I have an NVIDIA 2080 graphics card. My code: https://pastebin.com/zdLtFvEs Output: C:\Users\Intrinsix\jukebox>python Intrinsix.py C:\Users\Intrinsix\jukebox\jukebox\utils\gcs_utils.py:41: SyntaxWarning: "is not" with a literal. Did you mean "!="? outputs = [output for output in outputs if output is not ''] Using cuda True
> 
> C:\Users\Intrinsix\jukebox>python Intrinsix.py Using cuda True Downloading from gce Traceback (most recent call last): File "Intrinsix.py", line 32, in vqvae = make_vqvae(setup_hparams(vqvae, dict(sample_length = 1048576)), device) File "C:\Users\Intrinsix\jukebox\jukebox\make_models.py", line 95, in make_vqvae restore_model(hps, vqvae, hps.restore_vqvae) File "C:\Users\Intrinsix\jukebox\jukebox\make_models.py", line 55, in restore_model checkpoint = load_checkpoint(checkpoint_path) File "C:\Users\Intrinsix\jukebox\jukebox\make_models.py", line 34, in load_checkpoint download(gs_path, local_path) File "C:\Users\Intrinsix\jukebox\jukebox\utils\gcs_utils.py", line 36, in download subprocess.call(args) File "C:\Users\Intrinsix\miniconda3\lib\subprocess.py", line 340, in call with Popen(*popenargs, **kwargs) as p: File "C:\Users\Intrinsix\miniconda3\lib\subprocess.py", line 854, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Users\Intrinsix\miniconda3\lib\subprocess.py", line 1307, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] The system cannot find the file specified

https://www.microsoft.com/en-us/software-download/windows8ISO
