### ISSUE TITLE
Modify Google Colab to save checkpoints more frequently?

### ISSUE THREAD

**Issue by J-Miller1** [openai/jukebox#153]
I've been trying to upsample a rather long item on SMarioMan's modified colab for several days now. Every time I try, something ends up going wrong while upsampling to level 0 and every time I end up back at the same checkpoint about 1/6th of the way through level 0. One time I made it almost to the end before Google restricted my GPU access but it never saves any more checkpoints beyond that one point.

So I was wondering if there is any way to modify the code to save checkpoints more frequently so I could make some progress on this. However I have very little experience with Python so I don't know where to start.

Any help would be appreciated. Thanks.

**Comment by acsdog** [comment]
I too would be interested in this feature. I've been running it on colab and have the same issues. I have also had the page go unresponsive at times, leading to lost progress.

I'd also like to know if the upsampling stage requires 16GB of VRAM, or if it's just required for making the level 2 samples with 5b_lyrics. I have a 2060 SUPER 8GB and I can get a Jupyter Notebook server running, so if I can use Google's GPUs for level 2 and do the rest on my machine, I won't have to worry about getting disconnected anymore.

**Comment by DigestContent0** [comment]
A good solution to this is to interrupt(stop) the execution, start it again, wait for the error message to show up, then restart and run all.
