### ISSUE TITLE
Jukebox error when running the model.

### ISSUE THREAD

**Issue by Randy1435** [openai/jukebox#173]
I am using google colab to run this but since today I can't run it.
I think that this is an issue on their side.

It is a "File not found" error but when I click the link then it just downloaded the file.

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-6-d8cd9b2b81be> in <module>()
     12 
     13 vqvae, *priors = MODELS[model]
---> 14 vqvae = make_vqvae(setup_hparams(vqvae, dict(sample_length = 1048576)), device)
     15 top_prior = make_prior(setup_hparams(priors[-1], dict()), vqvae, device)

5 frames
/usr/local/lib/python3.6/dist-packages/torch/serialization.py in __init__(self, name, mode)
    209 class _open_file(_opener):
    210     def __init__(self, name, mode):
--> 211         super(_open_file, self).__init__(open(name, mode))
    212 
    213     def __exit__(self, *args):

FileNotFoundError: [Errno 2] No such file or directory: 'https://openaipublic.blob.core.windows.net/jukebox/models/5b/vqvae.pth.tar'
```
When I download the file and put it in my gdrive and point towards that I get this error.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-6b4098c77718> in <module>()
     13 vqvae, *priors = MODELS[model]
     14 vqvae = '/content/gdrive/My Drive/Jukebox/vqvae.pth.tar'
---> 15 top_prior = make_prior(setup_hparams(priors[-1], dict()), vqvae, device)

/usr/local/lib/python3.6/dist-packages/jukebox/make_models.py in make_prior(hps, vqvae, device)
    113     from jukebox.prior.prior import SimplePrior
    114 
--> 115     prior_kwargs = dict(input_shape=(hps.n_ctx,), bins=vqvae.l_bins,
    116                         width=hps.prior_width, depth=hps.prior_depth, heads=hps.heads,
    117                         attn_order=hps.attn_order, blocks=hps.blocks, spread=hps.spread,

AttributeError: 'str' object has no attribute 'l_bins'
```
I do not have any experience with python.

**Comment by acsdog** [comment]
Getting the same error here. Either the directory was changed and the colab notebook just hasn't been updated, or their server is down at the moment. Unfortunately I'm not sure if we can find the trained model elsewhere. Might just have to wait.

**Comment by acsdog** [comment]
I'm able to download the file by pasting the directory in my browser. Maybe try downloading it to gdrive and changing the directory in colab? I'll let you know if it works.

**Comment by Randy1435** [comment]
> Getting the same error here. Either the directory was changed and the colab notebook just hasn't been updated, or their server is down at the moment. Unfortunately I'm not sure if we can find the trained model elsewhere. Might just have to wait.

I have already waited more than 6 hours. Not saying that I am getting impatient. It's just stupid.

**Comment by acsdog** [comment]
Actually since it can be downloaded I really don't know what's wrong. Hopefully someone with a better understanding of the code can figure this out.

**Comment by Randy1435** [comment]
> Actually since it can be downloaded I really don't know what's wrong. Hopefully someone with a better understanding of the code can figure this out.

Yeah, Let the 500 iq big brains come here. I'm going to go sleep now. I'll look if it is available then when I wake up.

**Comment by tdunity** [comment]
Getting the same issue. I ran that exact cell around six to seven hours ago with no issues, but I noticed about an hour ago it stopped working. Not sure what changed.

**Comment by perlman-izzy** [comment]
Ditto ^

**Comment by tdunity** [comment]
The update model paths merge done around 10 hours ago seems to be the culprit, changing the values back to what they were before the merge should make the colab run without issues. I'm not a coder by any means, and I'm sure the merge was done for good reason, so consider this a temporary band-aid fix until we get someone who knows what they're doing to comment on the issue.

**Comment by Merzmensch** [comment]
@tdunity where could you access hparams.py in the Colab (in which folder is this file).

**Comment by Randy1435** [comment]
> The update model paths merge done around 10 hours ago seems to be the culprit, changing the values in hparams.py back to what they were before the merge let the colab run without errors in my case. I'm not a coder by any means, and I'm sure the merge was done for good reason, so consider this a temporary band-aid fix until we get someone who knows what they're doing to comment on the issue.

Can you please specify what the original hyperparams values are`? and where the folder is?

**Comment by tdunity** [comment]
Since it pulls the hyperparams from the jukebox repository, I just made a copy of it and got the hparams file from the version history. From there, I edited this line
`!pip install git+https://github.com/openai/jukebox.git`
to point to my own repository,
`!pip install git+https://github.com/tdunity/fixedjukebox.git`
If you want to use it, I'm pretty sure you can just edit the line in your own colab. I imagine there are much easier workarounds, but this is what worked for me.

**Comment by Randy1435** [comment]
> !pip install git+https://github.com/tdunity/fixedjukebox.git

I will look if it works. I'll also mention if it doesn't.

**Comment by Randy1435** [comment]
> Since it pulls the hyperparams from the jukebox repository, I just made a copy of it and got the hparams file from the version history. From there, I edited this line
> `!pip install git+https://github.com/openai/jukebox.git`
> to point to my own repository,
> `!pip install git+https://github.com/tdunity/fixedjukebox.git`
> If you want to use it, I'm pretty sure you can just edit the line in your own colab. I imagine there are much easier workarounds, but this is what worked for me.

It does indeed work. Thank you!

**Comment by prafullasd** [comment]
Just pushed a fix, can you check if it works for you with our repository again now?

**Comment by prafullasd** [comment]
It might download slowly, so do wait for it to finish. I'll look into speeding up the download

**Comment by Randy1435** [comment]
> Just pushed a fix, can you check if it works for you with our repository again now?

Sorry for the late response.
Yes. I coincidentally tried to do this and it works!
What exactly caused the the problem?

**Comment by Randy1435** [comment]
Hi, after 8 minutes the cell is still running, It got stuck on

`Running  wget -O /root/.cache/jukebox/models/5b_lyrics/prior_level_2.pth.tar https://openaipublic.blob.core.windows.net/jukebox/models/5b_lyrics/prior_level_2.pth.tar`

**Comment by Randy1435** [comment]
> The biggest models might download slowly (4-5 min), so do wait for it to finish. I'll look into speeding up the downloads

Hi, It has been running for 20 minutes

**Comment by prafullasd** [comment]
@Randy1435 I changed the link to download from a CDN. Try with the the latest version of the code (you'll need to restart/refresh the notebook), hopefully its faster!

**Comment by Randy-H0** [comment]
> @Randy1435 I changed the link to download from a CDN. Try with the the latest version of the code (you'll need to restart/refresh the notebook), hopefully its faster!

It is! Thank you for the helping hand!
