### ISSUE TITLE
RuntimeError: Failed to initialize NCCL

### ISSUE THREAD

**Issue by Jovonni** [openai/jukebox#18]
Running into

```bash
Caught error during NCCL init (attempt 0 of 5): Distributed package doesn't have NCCL built in
Caught error during NCCL init (attempt 1 of 5): Distributed package doesn't have NCCL built in
Caught error during NCCL init (attempt 2 of 5): Distributed package doesn't have NCCL built in
Caught error during NCCL init (attempt 3 of 5): Distributed package doesn't have NCCL built in
Caught error during NCCL init (attempt 4 of 5): Distributed package doesn't have NCCL built in
Traceback (most recent call last):
  File "jukebox/sample.py", line 237, in <module>
    fire.Fire(run)
  File "/Users/user/anaconda/envs/jukebox/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/Users/user/anaconda/envs/jukebox/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/Users/user/anaconda/envs/jukebox/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "jukebox/sample.py", line 229, in run
    rank, local_rank, device = setup_dist_from_mpi(port=port)
  File "/Users/user/Documents/projects/jukebox/jukebox/utils/dist_utils.py", line 86, in setup_dist_from_mpi
    raise RuntimeError("Failed to initialize NCCL")
RuntimeError: Failed to initialize NCCL
```
Specifically it is stating:
```bash
Distributed package doesn't have NCCL built in
```

From running
```bash
python jukebox/sample.py --model=1b_lyrics --name=sample_5b --levels=3 --sample_length_in_seconds=20 --total_sample_length_in_seconds=18/0 --sr=44100 --n_samples=6 --hop_fraction=0.5,0.5,0.125
```

Seems to be coming from
https://github.com/openai/jukebox/blob/2705dc07b29439b23fab5b4d6e85597ad7d90da3/jukebox/utils/dist_utils.py#L42

Here is where it is raised:
https://github.com/openai/jukebox/blob/2705dc07b29439b23fab5b4d6e85597ad7d90da3/jukebox/utils/dist_utils.py#L69-L86

Is the problem regarding my python distribution?

**Comment by Jovonni** [comment]
Or does it have something to do with certain environment variables not being set?

seen here, in the same function:
https://github.com/openai/jukebox/blob/2705dc07b29439b23fab5b4d6e85597ad7d90da3/jukebox/utils/dist_utils.py#L51-L57

**Comment by Jovonni** [comment]
Reading up on this here: 
https://developer.nvidia.com/nccl

**Comment by pavelkang** [comment]
@Jovonni did you find a solution to it?

**Comment by bsturk** [comment]
Wondering the same thing, I'm getting this with a colab that attempts to train a new model.

**Comment by noamlima** [comment]
make a function to return the variable values

**Comment by noamlima** [comment]
java is better to runing that if you have permission decompile the c code and dont read it just compile it to assembly with a.i or something

**Comment by noamlima** [comment]
then use java to compile python or remake python function in java

**Comment by isaqueseneda** [comment]
can somebody please just turn this into a drag and drop interface

**Comment by bradharms** [comment]
I had to make an nvidia developer account to download nccl. But then it seemed to only provide packages for linux distros. The system with my high-powered GPU isn't running linux, so I think I would have to install Ubuntu in multi-boot to get any further with this. I'm not going to do that right now though. :)

**Comment by scottvr** [comment]
Just in case there's anyone who, like me, finds themselves years later trying to run this code and encounters this error, I started to write this up, forgot about it, then found this in my LibreOffice recovery files so linked it since it does explain and offer a simple solution to this error. https://www.paperclipmaximizer.ai/jukeboxfix.html

**Comment by yvonneleoo** [comment]
> Just in case there's anyone who, like me, finds themselves years later trying to run this code and encounters this error, I started to write this up, forgot about it, then found this in my LibreOffice recovery files so linked it since it does explain and offer a simple solution to this error. https://www.paperclipmaximizer.ai/jukeboxfix.html

Thank you! It does work. You save my day.

**Comment by scottvr** [comment]
> > Just in case there's anyone who, like me, finds themselves years later trying to run this code and encounters this error, I started to write this up, forgot about it, then found this in my LibreOffice recovery files so linked it since it does explain and offer a simple solution to this error. https://www.paperclipmaximizer.ai/jukeboxfix.html
> 
> Thank you! It does work. You save my day.

I am glad it helped you. Thanks for letting me know.
