### ISSUE TITLE
Level:2, Cond downsample:None, Raw to tokens:128, Sample length:786432 Downloading from gce Killed

### ISSUE THREAD

**Issue by JoeThanks67** [openai/jukebox#200]
`root@ea984bce3cef:/opt/jukebox# python jukebox/sample.py --model=1b_lyrics --name=foobar --levels=3 --sample_length_in_seconds=20 --total_sample_length_in_seconds=180 --sr=44100 --n_samples=1 --hop_fraction=0.5,0.5,0.125

[[46264,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: ea984bce3cef

Another transport will be used instead, although this may result in
lower performance.

NOTE: You can disable this warning by setting the MCA parameter
btl_base_warn_component_unused to 0.

Using cuda True
{'name': 'foobar', 'levels': 3, 'sample_length_in_seconds': 20, 'total_sample_length_in_seconds': 180, 'sr': 44100, 'n_samples': 1, 'hop_fraction': (0.5, 0.5, 0.125)}
Setting sample length to 881920 (i.e. 19.998185941043083 seconds) to be multiple of 128
Downloading from gce
Restored from /root/.cache/jukebox-assets/models/5b/vqvae.pth.tar
0: Loading vqvae in eval mode
Using apex FusedLayerNorm
Conditioning on 1 above level(s)
Checkpointing convs
Checkpointing convs
Loading artist IDs from /opt/jukebox/jukebox/data/ids/v2_artist_ids.txt
Loading artist IDs from /opt/jukebox/jukebox/data/ids/v2_genre_ids.txt
Level:0, Cond downsample:4, Raw to tokens:8, Sample length:65536
Downloading from gce
Restored from /root/.cache/jukebox-assets/models/5b/prior_level_0.pth.tar
0: Loading prior in eval mode
Conditioning on 1 above level(s)
Checkpointing convs
Checkpointing convs
Loading artist IDs from /opt/jukebox/jukebox/data/ids/v2_artist_ids.txt
Loading artist IDs from /opt/jukebox/jukebox/data/ids/v2_genre_ids.txt
Level:1, Cond downsample:4, Raw to tokens:32, Sample length:262144
Downloading from gce
Restored from /root/.cache/jukebox-assets/models/5b/prior_level_1.pth.tar
0: Loading prior in eval mode
Creating cond. autoregress with prior bins [79, 2048], 
dims [384, 6144], 
shift [ 0 79]
input shape 6528
input bins 2127
Self copy is False
Loading artist IDs from /opt/jukebox/jukebox/data/ids/v3_artist_ids.txt
Loading artist IDs from /opt/jukebox/jukebox/data/ids/v3_genre_ids.txt
Level:2, Cond downsample:None, Raw to tokens:128, Sample length:786432
Downloading from gce
Killed`

**Comment by btrude** [comment]
See my comment here: https://github.com/openai/jukebox/issues/9#issuecomment-648768947

**Comment by JoeThanks67** [comment]
Solved with an update to the latest version that loads from Azure. 

[https://github.com/openai/jukebox/commit/19533750203c5f5532688d7fcbc2c357b36a67b7 Fix model downloads](https://github.com/openai/jukebox/commit/19533750203c5f5532688d7fcbc2c357b36a67b7)

**Comment by JoeThanks67** [comment]
Solved with an update to the latest version that loads from Azure. 

[https://github.com/openai/jukebox/commit/19533750203c5f5532688d7fcbc2c357b36a67b7](https://github.com/openai/jukebox/commit/19533750203c5f5532688d7fcbc2c357b36a67b7)
