### ISSUE TITLE
NVIDIA-SMI failure (Google CoLab Pro)

### ISSUE THREAD

**Issue by Butts-McGee** [openai/jukebox#205]
I was tired of the 12 hour GPU limit on Google Colab, so I caved and bought Colab Pro. However, ever since I did that, Jukebox has decided to stop working. Every time I try to run the first cell, it says "NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running." I barely know anything about code, so I have no idea what to do. Any help?

**Comment by Butts-McGee** [comment]
I figured it out. I had to go to **Change Hardware Type** and set **Hardware Accelerator** to **GPU**.

**Comment by sanssoleilfilm** [comment]
where do you change hardware type?

**Comment by Mustafaaji18** [comment]
actually you can change it to Edit > Notebook settings and selecting GPU as hardware accelerator.
