### ISSUE TITLE
Regarding the copyrights of the model weights

### ISSUE THREAD

**Issue by ssrp** [openai/jukebox#22]
Hi, thank you for the code/models, the work is very interesting!
I'd like to know regarding the copyrights on model weights. If in case you have trained the models on copyrighted music, are we allowed to use the weights for commercial purposes (since MIT license allows commercial usage)?
Thank you!

**Comment by kylemcdonald** [comment]
I've also been wondering this. My understanding is that:

1. OpenAI has not released the weights under any specific license. The weights are not explicitly part of the code.
2. The weights were trained on copyrighted material. OpenAI has argued that training is fair use, especially for their non-commercial research work. This hasn't really been decided in the courts yet.
3. Even if OpenAI explicitly granted a license to the weights allowing commercial use, it might still be possible to use the weights in a way that break copyright/fair use. But this might be more of a theoretical problem than a practical problem.

**Comment by prafullasd** [comment]
The license has been updated to cover both the released weights and code, and is a non-commercial use license.

**Comment by nathanielvirgo** [comment]
What about the audio samples provided at https://jukebox.openai.com/?song=789408142 ? Are those released under a license that allows reuse?
