### ISSUE TITLE
Out of RAM on 32GB + RTX A4000 machine while trying to launch the sampling from scratch

### ISSUE THREAD

**Issue by surpscare** [openai/jukebox#260]
After downloading the prior level models, Jukebox goes to 0:" Loading prior in eval mode" and then RAM consumption slowly reaches the maximum of 32GB and then the process crashes returning zsh: killed     python jukebox/sample.py --model=5b_lyrics --name=sample_5b --levels=3
As it can be seen in Google Colab, the Jukebox nearly utilizes only the allocated 12.7 GB RAM and even doesn't reach the maximum, so I want to know where might be the issue. Possibly I have misconfigured it somehow (but it is done right by instructions from the title page) and it doesn't utilize the VRAM at all (the VRAM graph does not show any significant consumption, it just increases for ~400MB at the beginning and returns back after crashing)

Used command:
```
python jukebox/sample.py --model=5b_lyrics --name=sample_5b --levels=3 --sample_length_in_seconds=20 \
--total_sample_length_in_seconds=80 --sr=44100 --n_samples=2 --hop_fraction=0.5,0.5,0.125
```

System:

```
██████████████████  ████████   fubar@perkele 
██████████████████  ████████   ------------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Kernel: 5.19.1-3-MANJARO 
████████            ████████   Uptime: 2 hours, 14 mins 
████████  ████████  ████████   Packages: 1196 (pacman) 
████████  ████████  ████████   Shell: bash 5.1.16 
████████  ████████  ████████   Resolution: 2560x1440 
████████  ████████  ████████   DE: Plasma 5.24.6 
████████  ████████  ████████   WM: KWin 
████████  ████████  ████████   Theme: [Plasma], Breeze [GTK2/3] 
████████  ████████  ████████   Icons: [Plasma], breeze [GTK2/3] 
████████  ████████  ████████   Terminal: konsole 
████████  ████████  ████████   CPU: AMD Ryzen 7 PRO 2700 (16) @ 3.200GHz 
                               GPU: NVIDIA RTX A4000 
                               Memory: 2359MiB / 32006MiB 

```

Also while trying to operate it through Interacting_with_Jukebox.ipynb file, the GIT import cell just breaks down the existing instance of Jukebox and it now returns the error 
```
Traceback (most recent call last):
  File "jukebox/sample.py", line 8, in <module>
    from jukebox.utils.audio_utils import save_wav, load_audio
  File "/home/fubar/jukebox/jukebox/utils/audio_utils.py", line 4, in <module>
    import soundfile
  File "/home/fubar/miniconda3/envs/jukebox/lib/python3.7/site-packages/soundfile.py", line 17, in <module>
    from _soundfile import ffi as _ffi
  File "/home/fubar/miniconda3/envs/jukebox/lib/python3.7/site-packages/_soundfile.py", line 2, in <module>
    import _cffi_backend
ImportError: libffi.so.7: cannot open shared object file: No such file or directory
```

and only deleting the folder and reestablishing of the jukebox instance returnsit to the previous state.

**Comment by surpscare** [comment]
https://user-images.githubusercontent.com/63161216/188334032-dcd4a3df-ba08-4485-8b8f-f2cf6e42ca2a.mp4

**Comment by Postconceptlab** [comment]
same error i guess

**Comment by surpscare** [comment]
The solution was to launch Jukebox from jupyter notebook instead of running from zsh, but I have encountered an another obstacle which will be covered in the next issue.

**Comment by surpscare** [comment]
obstacle which will be covered in the next issue.

**Comment by surpscare** [comment]
The solution was to launch the Jukebox from the Jupyter notebook interacting_with_jukebox.ipynb, but now I have hit another obstacle which will be covered in the next issue.
