### ISSUE TITLE
Colab crashes after using all avilable RAM

### ISSUE THREAD

**Issue by Bruh-byte** [openai/jukebox#27]
![Screenshot_2020-05-03 Google Colaboratory](https://user-images.githubusercontent.com/57909011/80917505-00ef0100-8d68-11ea-904e-a8e8a973e4a8.png)
![Screenshot_2020-05-03 Google Colaboratory(1)](https://user-images.githubusercontent.com/57909011/80917515-27ad3780-8d68-11ea-9fdb-45cac123fe57.png)
On the model loading step

**Comment by Jovonni** [comment]
This isn’t an issue with the repo, it’s your collab environment 

Can you put the code for the cells crashing it?

**Comment by Bruh-byte** [comment]
> 
> 
> This isn’t an issue with the repo, it’s your collab environment
> 
> Can you put the code for the cells crashing it?

model = "5b_lyrics" # or "1b_lyrics"     
hps = Hyperparams()
hps.sr = 44100
hps.n_samples = 3 if model=='5b_lyrics' else 8
hps.name = 'samples'
chunk_size = 16 if model=="5b_lyrics" else 32
max_batch_size = 3 if model=="5b_lyrics" else 16
hps.levels = 3
hps.hop_fraction = [.5,.5,.125]

vqvae, *priors = MODELS[model]
vqvae = make_vqvae(setup_hparams(vqvae, dict(sample_length = 1048576)), device)
top_prior = make_prior(setup_hparams(priors[-1], dict()), vqvae, device)

**Comment by Bruh-byte** [comment]
Chose 1b version
