### ISSUE TITLE
Missing hyperparams example for newly trained top-level prior

### ISSUE THREAD

**Issue by iRyanBell** [openai/jukebox#39]
The documentation reads:

> You can then run sample.py with the top-level of our models replaced by your new model. To do so, add an entry my_model in MODELs (in make_models.py) with the (vqvae hps, upsampler hps, top-level prior hps) of your new model, and run sample.py with --model=my_model.

Following these directions leads to a hparams.py `Key Error` for the missing top-level prior definition. Using `small_prior`'s hps leads to an error: `Expecting (genre, artist) bins, got {y_bins}`. Adding a `y_bins: (0,0)` param leads to further issues with the labeling.

It isn't quite clear how to transition between training a model, specifying the path to this model, and getting sound out.

**Comment by prafullasd** [comment]
Was the new top-level prior trained without labels? If it was trained with no labels, you want to pass labels=False in the small_prior hps too, as it seems the model is trying to make a labeller object when it shouldn't.  

Note you'll still need to pass an (artist, genre) label while using the upsampling levels, though it should be fine to use 0,0 ie unknown for those as the upsampling doesn't depend too strongly on the labels.

**Comment by prafullasd** [comment]
The small_prior only provides a base set of values to start from, you want to add specific values for labels, t_ranges etc for the model you trained when you load it. Might be easier to get them directly from the saved checkpoint, since that saves the hps too.

**Comment by gogobd** [comment]
I was trying the same, added "labels=False" in params.py for small_vqvae, small_prior and small_upsampler but got stuck:

```
/jukebox# python jukebox/sample.py --model=my_model --name=sample_my_model --levels=3 --sample_length_in_seconds=20 --tot
al_sample_length_in_seconds=180 --sr=44100 --n_samples=6 --hop_fraction=0.5,0.5,0.125
Using cuda True
{'name': 'sample_my_model', 'levels': 3, 'sample_length_in_seconds': 20, 'total_sample_length_in_seconds': 180, 'sr': 44100, 'n_sample
s': 6, 'hop_fraction': (0.5, 0.5, 0.125)}
Setting sample length to 440832 (i.e. 19.99238095238095 seconds) to be multiple of 256
0: Loading vqvae in eval mode
Conditioning on 1 above level(s)
Checkpointing convs
Level:0, Cond downsample:2, Raw to tokens:2, Sample length:16384
0: Loading prior in eval mode
Conditioning on 1 above level(s)
Level:0, Cond downsample:2, Raw to tokens:2, Sample length:16384
0: Loading prior in eval mode
Traceback (most recent call last):
  File "jukebox/sample.py", line 275, in <module>
    fire.Fire(run)
  File "/opt/miniconda/lib/python3.7/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/opt/miniconda/lib/python3.7/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/opt/miniconda/lib/python3.7/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "jukebox/sample.py", line 272, in run
    save_samples(model, device, hps, sample_hps)
  File "jukebox/sample.py", line 223, in save_samples
    labels = [prior.labeller.get_batch_labels(metas, 'cuda') for prior in priors ]
  File "jukebox/sample.py", line 223, in <listcomp>
    labels = [prior.labeller.get_batch_labels(metas, 'cuda') for prior in priors ]
  File "/opt/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'SimplePrior' object has no attribute 'labeller'
/jukebox# 
```

How can I avoid this?
