### ISSUE TITLE
Unexpected EOF when creating Upsamplers

### ISSUE THREAD

**Issue by ayushmore** [openai/jukebox#57]
I am running into this error when creating the upsamplers. I am not sure which file it is referring to that could potentially be corrupted. All the code before worked well and I have my music samples. 

I am using the colab notebook that SMarioMan provided for primed audio. 

![eofError](https://user-images.githubusercontent.com/22268454/81493719-a964ff80-9257-11ea-8b96-55a6ed8c61ae.PNG)

**Comment by prafullasd** [comment]
You need to delete and redownload the model checkpoints, they're stored in ~/.cache/jukebox-assets/

**Comment by maatisaUNC** [comment]
I'm getting the same error as well. Can you explain step by step what I need to do. I'm still relatively new to this. 

How do I redownload after I delete the model checkpoints?

Thanks

**Comment by prafullasd** [comment]
If you rerun the script it'll download them again
