### ISSUE TITLE
Loading Previous Model after timeout

### ISSUE THREAD

**Issue by ayushmore** [openai/jukebox#64]
Is there some way to upload the model back into Colab instead of restarting? I believe it is saved as data.pth.tar but I am not sure how to resume with the samples I created when Google Colab disconnects. I have samples at level 1 but it does not complete upsampling to level 0. 

Thank you for the help!

**Comment by kcrosley-leisurelabs** [comment]
Check out https://github.com/openai/jukebox/issues/40#issuecomment-627532530
