### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by InterestingMuck** [openai/jukebox#66]
Will the code ever be improved upon to be faster? I understand there is limits to AI but i'm sure theres a solution to make upsampling faster

**Comment by kcrosley-leisurelabs** [comment]
Possible solutions are described in the paper. Check it out.

**Comment by InterestingMuck** [comment]
too lazy lol. why dont you make it faster for me?

**Comment by Randy1435** [comment]
That's blatantly rude and no. there is currently NO WAY to make it faster. Even while using google it takes really long.
