### ISSUE TITLE
The colab link in the README requires access.

### ISSUE THREAD

**Issue by nsthorat** [openai/jukebox#7]
This link is restricted: https://colab.research.google.com/drive/1IQcUNjxLs79YVKLF-A8ghFLCaVYHjc4v

**Comment by ZurMaD** [comment]
![image](https://user-images.githubusercontent.com/28235457/80736692-16e69280-8ad8-11ea-959c-36f46e04835a.png)
Same here

**Comment by Bruh-byte** [comment]
Same

**Comment by loretoparisi** [comment]
It seems they have temporary removed colab notebook.

**Comment by mcleavey** [comment]
Sorry for the delay, the link is now open here: https://colab.research.google.com/github/openai/jukebox/blob/master/jukebox/Interacting_with_Jukebox.ipynb

**Comment by Jovonni** [comment]
@mcleavey I am not seeing info on training a new model in that notebook
