### ISSUE TITLE
Problem running installation instructions

### ISSUE THREAD

**Issue by maraoz** [openai/jukebox#8]
When I run this:
```
conda install pytorch=1.4 torchvision=0.5 cudatoolkit=10.0 -c pytorch
```

I get:
```
PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit=10.0
Current channels:

  - https://conda.anaconda.org/pytorch/osx-64
  - https://conda.anaconda.org/pytorch/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

I did as the error suggested but I couldn't find the package cudatoolkit v10+ for OS X. (https://anaconda.org/anaconda/cudatoolkit)

Any ideas on how to solve this?

**Comment by maraoz** [comment]
ok I found this: https://developer.nvidia.com/cuda-10.0-download-archive?target_os=MacOSX&target_arch=x86_64&target_version=1013&target_type=dmglocal
I'll try installing that

**Comment by gsastry** [comment]
@maraoz I also see a 10.0 for osx54 [here](https://anaconda.org/numba/cudatoolkit/files)

**Comment by maraoz** [comment]
@gsastry that worked, thanks!

**Comment by Jovonni** [comment]
> @gsastry that worked, thanks!

How did you install that though? I downloaded the zip/tar. Do we need to follow this on MacOS?
[CUDA Install osx](https://developer.download.nvidia.com/compute/cuda/10.0/Prod/docs/sidebar/CUDA_Installation_Guide_Mac.pdf)

**Comment by maraoz** [comment]
@Jovonni I did this: https://stackoverflow.com/a/45167575 with the .tar.bz2 found here: osx-64/cudatoolkit-10.0-0.tar.bz2

I didn't run `conda install pytorch=1.4 torchvision=0.5 cudatoolkit=10.0 -c pytorch` after that though, and I still can't make this project work.

**Comment by Jovonni** [comment]
For anyone running into this, got past this by running:
```bash
conda install <location of bundle>/cudatoolkit-10.0-0.tar.bz2
```

After downloading the correct cudatoolkit version from the link @maraoz sent.
