### ISSUE TITLE
How do you sample and train your own music in Google Colab?

### ISSUE THREAD

**Issue by briancpark** [openai/jukebox#88]
Hi,

I wanted to test out this library with my own samples of music. I don't have a dedicated GPU on my local machine, so I wanted to try this with Google Colab. I can't seem to find the directory where samples should be loaded and not clear on how to run on your own custom music files?

If the Google Colab is purely for demo, I can try to initialize a compute engine/VM under Google Cloud Platform. If anyone can give recommended configurations for a GCP compute engine, that would be greatly appreciated!

**Comment by perlickr** [comment]
I would like to do the same thing!

**Comment by perlickr** [comment]
This has been closed - I found the the code was updated to include your own tracks in the 'pull requests' section! (I'm a newb here btw .. sorry if I'm not writing this right)

**Comment by briancpark** [comment]
@perlickr Thanks for pointing it out! Yes, @SMarioMan has created a [pull request](https://github.com/openai/jukebox/pull/72) that hasn't been approved yet. I will try this and see if it works. For others wanting to do this, you can do `git clone https://github.com/SMarioMan/jukebox` and import the `.ipynb` file to Google Colab

**Comment by SMarioMan** [comment]
Google Colab has native integration with GitHub, so until my PR is approved, you can use the workbook directly at https://colab.research.google.com/github/SMarioMan/jukebox/blob/master/jukebox/Interacting_with_Jukebox.ipynb
