### ISSUE TITLE
py", line 581, in _load      deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)  RuntimeError: unexpected EOF, expected 20664312 more bytes. The file might be corrupted.  terminate called after throwing an instance of 'c10::Error'

### ISSUE THREAD

**Issue by perlman-izzy** [openai/jukebox#98]
Running on a Vast.AI server, 4x GTX 1080 Ti/ Xeon® E5-2650 0/ 16.0/16 cores
64/64 GB

Program runs for about 2-3 minutes and throws the following error: Any help appreciated.

py", line 581, in _load

    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)

RuntimeError: unexpected EOF, expected 20664312 more bytes. The file might be corrupted.

terminate called after throwing an instance of 'c10::Error'

  what():  owning_ptr == NullType::singleton() || owning_ptr->refcount_.load() > 0 ASSERT FAILED at /opt/conda/conda-bld/pytorch_1556653114079/work/c10/util/intrusive_ptr.h:350, please report a bug to PyTorch. intrusive_ptr: Can only intrusive_ptr::reclaim() owning pointers that were created using intrusive_ptr::release(). (reclaim at /opt/conda/conda-bld/pytorch_1556653114079/work/c10/util/intrusive_ptr.h:350)

frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7fc5a1c8ddc5 in /opt/conda/envs/jukebox/lib/python3.7/site-packages/torch/lib/libc10.so)

frame #1: THStorage_free + 0xca (0x7fc5a29d120a in /opt/conda/envs/jukebox/lib/python3.7/site-packages/torch/lib/libcaffe2.so)

frame #2: <unknown function> + 0x14872d (0x7fc5d0cb272d in /opt/conda/envs/jukebox/lib/python3.7/site-packages/torch/lib/libtorch_python.so)

<omitting python frames>

frame #26: __libc_start_main + 0xf0 (0x7fc5df535830 in /lib/x86_64-linux-gnu/libc.so.6)

Aborted (core dumped)

**Comment by thisIsTheFoxe** [comment]
Hi,
I think I ran into a similar issue.. do you remember which model you used?

**Comment by prafullasd** [comment]
See #25, your model checkpoint got corrupted so you need to delete the downloaded checkpoints from the cache and redownload.
